---
# tasks file for ansible-role-module-marathon

- name: call marathon module
  marathon:
    marathon_uri: "{{ item.marathon_url|default('https://localhost/') }}"
    app_id: "{{ item.app_id }}"
    app_json: "{{ item.app_json }}"
  with_items: "{{ app_ids|default([]) }}"
